server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        #        name: JSESSIONID
        #        domain: earthonline.asia      # 可选：让子域共享登录态
        #        path: /api
        #        http-only: true
        #        secure: true                  # HTTPS 才能用 Secure
        #        same-site: none               # 允许跨域携带
        max-age: 2592000              # 30 天
spring:
  application:
    name: yu-picture-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deng_picture
    username: root
    password: dc123456
  # Redis 配置
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
  #   数据库配置
  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://localhost:3306/duola_picture
  #    username: duola
  #    password: dc123456
  #  # Redis 配置
  #  redis:
  #    database: 0
  #    host: localhost
  #    port: 6379
  #    timeout: 5000
  #    password: dc123456
  # Session 配置
  session:
    store-type: redis
    # session 30 天后过期
    timeout: 2592000
  # 开放更大的文件上传体积
  servlet:
    multipart:
      max-file-size: 10MB
  # 空间图片分表
  shardingsphere:
    datasource:
      names: deng_picture
      deng_picture:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/duola_picture
        username: duola
        password: dc123456
    rules:
      sharding:
        tables:
          picture:
            actual-data-nodes: yu_picture.picture # 动态分表
            table-strategy:
              standard:
                sharding-column: spaceId
                sharding-algorithm-name: picture_sharding_algorithm  # 使用自定义分片算法
        sharding-algorithms:
          picture_sharding_algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.yupi.yupicturebackend.manager.sharding.PictureShardingAlgorithm
    props:
      sql-show: true
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # 仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    enable-sql-runner: true
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.yupi.yupicturebackend.controller
## 对象存储配置（需要从腾讯云获取）
